bot_name = "yeetmachine"

[metadata]
bot_authors = [ "@vardy", "@Arraying" ]
developer_ids = [ 115134128717955080 ]
github_link = "https://example.com"

[bot]
bot_token = "bot-token-here"
bot_token_beta = "oopsie doopsie doo"
beta_mode = true
bot_version = "x.y.z"
static_prefix = "."

[database]
db_ip = "localhost" # Name of database container
main_db = 12 # Integer 0-15 for Redis
main_password = ""
