version: '3'

services:
  socat:
    image: alpine/socat:1.0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - TCP-LISTEN:1234,fork
      - UNIX-CONNECT:/var/run/docker.sock

  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db, socat]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: https://ci.ibdiscord.team
      CONCOURSE_ADD_LOCAL_USER: admin:UJXKhkNw3%Zsc86WB9g#544qwjmQYw
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
      CONCOURSE_MAIN_TEAM_GITHUB_ORG: uqmc
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_GITHUB_CLIENT_ID: 0c895f67ce40cd769341
      CONCOURSE_GITHUB_CLIENT_SECRET: 71d9115187d57bedf296d5d3f28360fa67b006eb